# Generated by Django 2.2.1 on 2019-05-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20190516_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='CWURRank',
            field=models.IntegerField(blank=True, default=-1, null=True, unique=True),
        ),
    ]
