# Generated by Django 2.2.1 on 2019-05-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_auto_20190516_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='Name',
            field=models.CharField(max_length=1000),
        ),
    ]
