# Generated by Django 2.2.1 on 2019-05-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_auto_20190517_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(default='prenom.nom@insa-lyon.fr', help_text='Utilisez votre adresse INSA : prenom.nom@insa-lyon.fr', max_length=254),
        ),
    ]
