# Generated by Django 2.2.1 on 2019-05-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_auto_20190521_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitylanguages',
            name='LanguageDiploma',
            field=models.CharField(blank=True, help_text="Si vous n'avez pas passé de certification, ne remplissez pas ce champ.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='universitylanguages',
            name='LanguageLevel',
            field=models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('X', 'Non Specifie')], default='X', help_text="Si vous n'avez pas passé de certification, ne remplissez pas ce champ.", max_length=10, null=True),
        ),
    ]
