# Generated by Django 2.2.7 on 2019-11-09 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0016_university_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='Duration',
        ),
        migrations.RemoveField(
            model_name='university',
            name='Places',
        ),
        migrations.CreateModel(
            name='UniversityPlaces',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Duration', models.CharField(choices=[('S', 'Semestre'), ('A', 'Année'), ('X', 'Inconnu')], default='X', max_length=200)),
                ('Places', models.IntegerField(default=-1)),
                ('University', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.University')),
            ],
        ),
    ]
