# Generated by Django 2.2.7 on 2019-11-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0017_auto_20191109_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityplaces',
            name='Duration',
            field=models.CharField(choices=[('S', 'Semestre'), ('A', 'Année')], max_length=200),
        ),
    ]
