# Generated by Django 3.0.7 on 2020-06-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0021_auto_20191118_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='Comment',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
