# Generated by Django 2.2.1 on 2019-05-16 15:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CityName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CountryName', models.CharField(max_length=100)),
                ('ECTSConversion', models.FloatField(default=-1)),
                ('Continent', models.CharField(choices=[('AS', 'Asie'), ('AF', 'Afrique'), ('AdN', 'Amerique du Nord'), ('AdS', 'Amerique du Sud'), ('EU', 'Europe'), ('OC', 'Oceanie')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.IntegerField(default=-1)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Semester', models.IntegerField(default=-1)),
                ('Visa', models.BooleanField(default=False)),
                ('Comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('TimeVisa', models.DurationField(blank=True, default=datetime.timedelta, null=True)),
                ('Rent', models.IntegerField(blank=True, default=-1, null=True)),
                ('MonthlyExpenses', models.IntegerField(blank=True, default=-1, null=True)),
                ('NightLifeGrade', models.IntegerField(blank=True, default=-1, null=True)),
                ('CulturalLifeGrade', models.IntegerField(blank=True, default=-1, null=True)),
                ('Security', models.IntegerField(blank=True, default=-1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(default='prenom.nom@insa-lyon.fr', help_text='Utilisez votre adresse INSA : prenom.nom@insa-lyon.fr', max_length=254, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Surname', models.CharField(max_length=100)),
                ('INSADepartment', models.CharField(choices=[('BS', 'BS'), ('GCU', 'GCU'), ('GM', 'GM'), ('GE', 'GE'), ('TC', 'TC'), ('IF', 'IF'), ('SGM', 'SGM'), ('GEN', 'GEN'), ('GI', 'GI')], max_length=10)),
                ('Nationality', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('RankMetric', models.DecimalField(decimal_places=2, default=-1, max_digits=3)),
                ('LifeMetric', models.DecimalField(decimal_places=2, default=-1, max_digits=3)),
                ('Lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('Long', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('WebLink', models.URLField(default='https://pas.renseigne')),
                ('Places', models.IntegerField(default=-1)),
                ('Demand', models.IntegerField(default=-1)),
                ('SplitableYear', models.BooleanField(default=False)),
                ('Project', models.BooleanField(default=False)),
                ('CWURRank', models.IntegerField(blank=True, null=True, unique=True)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.City')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityLanguages',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Language', models.CharField(default='Inconnu', max_length=50)),
                ('LanguageDiploma', models.CharField(blank=True, max_length=200, null=True)),
                ('LanguageLevel', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('X', 'Non Specifie')], max_length=10, null=True)),
                ('University', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.University')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityContracts',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ContractType', models.CharField(choices=[('AR', 'Accord de Recherche'), ('AC', 'Accord Cadre'), ('DD', 'Double Diplome'), ('DDD', 'Double Diplome Doctorat'), ('DDMS', 'Double Diplome Master Specialise'), ('FITEC', 'FITEC'), ('M', 'Mobilite'), ('PDD', 'Procedure Double Diplome'), ('S', 'Specifique'), ('X', 'Inconnu')], default='X', max_length=200)),
                ('University', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.University')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAid',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, help_text='Le nom de la bourse.', max_length=100, null=True)),
                ('Value', models.IntegerField(blank=True, default=-1, help_text='En euros (€).', null=True)),
                ('ReceivedEvery', models.CharField(blank=True, choices=[('J', 'Jours'), ('S', 'Semaines'), ('M', 'Mois')], max_length=15, null=True)),
                ('Exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Exchange')),
            ],
        ),
        migrations.AddField(
            model_name='exchange',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Student'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='University',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.University'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='Inconnu', max_length=100)),
                ('Rank', models.IntegerField(default=-1, help_text='Utilisez une valeur entre 1 et 5, 1 étant la plus basse et 5 la plus haute.')),
                ('University', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.University')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Country'),
        ),
    ]
