# Generated by Django 2.2.1 on 2019-05-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_auto_20190517_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitylanguages',
            name='LanguageLevel',
            field=models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('X', 'Non Specifie')], default='X', max_length=10, null=True),
        ),
    ]
