# Generated by Django 2.2.1 on 2019-05-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_auto_20190521_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='Semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=-1),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='Year',
            field=models.IntegerField(choices=[(4, 4), (5, 5)], default=-1),
        ),
    ]
