# Generated by Django 2.2.1 on 2019-05-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_auto_20190522_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='CulturalLifeGrade',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='NightLifeGrade',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='Security',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='Semester',
            field=models.IntegerField(choices=[(1, 'S1'), (2, 'S2')], default=-1),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='Year',
            field=models.IntegerField(choices=[(4, '4TC'), (5, '5TC')], default=-1),
        ),
        migrations.AlterField(
            model_name='financialaid',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='financialaid',
            name='Value',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='universitylanguages',
            name='LanguageDiploma',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='universitylanguages',
            name='LanguageLevel',
            field=models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('X', 'Non Specifié')], default='X', max_length=10, null=True),
        ),
    ]
