# Generated by Django 2.2.1 on 2019-05-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_auto_20190522_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='CulturalLifeGrade',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='NightLifeGrade',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='Security',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=-1, null=True),
        ),
    ]
