# Generated by Django 2.2.1 on 2019-05-22 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0013_auto_20190522_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': (('noter_depart', "Creer et noter un département d'une université"),)},
        ),
    ]
