# Generated by Django 2.2.1 on 2019-05-29 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0014_auto_20190523_0022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniversityContracts',
            new_name='UniversityContractsAdmin',
        ),
        migrations.AddField(
            model_name='university',
            name='AvailableForBS',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='AvailableForGCU',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='AvailableForGE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='AvailableForGEN',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='AvailableForGI',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='AvailableForGM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='AvailableForIF',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='AvailableForSGM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='AvailableForTC',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UniversityContractsStudent',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ContractType', models.CharField(choices=[('DD', 'Double Diplome'), ('M', 'Mobilite')], default='X', max_length=200)),
                ('University', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.University')),
            ],
        ),
    ]
