# Generated by Django 2.2.7 on 2019-11-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0018_auto_20191109_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityplaces',
            name='Exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
